<?php

namespace Sky\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function findRandom()
    {
        $em = $this->getEntityManager();
        $rows = $em->createQuery('
                SELECT COUNT(s.id)
                FROM SkyTestBundle:Student s')
            ->getSingleScalarResult();

        $offset = max(0, rand(0, $rows - 2));

        $query = $em->createQuery('
                SELECT DISTINCT s
                FROM SkyTestBundle:Student s')
            ->setMaxResults(1)
            ->setFirstResult($offset);

        return $query->getResult();
    }
}
