<?php

namespace Sky\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository
{
    public function findAllPage(&$page = 1, &$pageSize = 10)
    {
        $query = "SELECT t FROM SkyTestBundle:Teacher t";
        $query = $this->getEntityManager()
            ->createQuery($query)
            ->setFirstResult($pageSize * ($page - 1))
            ->setMaxResults($pageSize);

        return new Paginator($query);
    }
}
