<?php

namespace Sky\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository
{
    public function findRandom()
    {
        $em = $this->getEntityManager();
        $rows = $em->createQuery('
                SELECT COUNT(t.id)
                FROM SkyTestBundle:Teacher t')
            ->getSingleScalarResult();

        $offset = max(0, rand(0, $rows - 2));

        $query = $em->createQuery('
                SELECT DISTINCT t
                FROM SkyTestBundle:Teacher t')
            ->setMaxResults(1)
            ->setFirstResult($offset);

        return $query->getResult();
    }
}
