sky_test_report_max_pair:
    path: /max_pair/{page}/{pageSize}
    defaults: { _controller: SkyTestBundle:Report:maxPair, page: 1, pageSize: 10 }
    requirements:
        page:  \d+
        pageSize: \d+

sky_test_report_teacher_pair:
    path: /teacher/pair/{firstId}/{secondId}
    defaults: { _controller: SkyTestBundle:Report:teacherPair }
    requirements:
        firstId: \d+
        secondId: \d+
