sky_test_student_new:
    path: /new
    defaults: { _controller: SkyTestBundle:Student:new  }

sky_test_student_index:
    path: /{id}
    defaults: { _controller: SkyTestBundle:Student:index  }
    requirements:
        id:  \d+