sky_test_teacher_new:
    path: /new
    defaults: { _controller: SkyTestBundle:Teacher:new  }

sky_test_teacher_list:
    path: /list/{page}/{pageSize}/{sortField}/{sortDirection}
    defaults: { _controller: SkyTestBundle:Teacher:list, page: 1, pageSize: 10, sortField: 'name', sortDirection: 'DESC' }
    requirements:
        page:  \d+
        pageSize: \d+
        sortField: name|count
        sortDirection: ASC|DESC

sky_test_teacher_delete:
    path: /{id}/delete/
    defaults: { _controller: SkyTestBundle:Teacher:delete }
    requirements:
        id:  \d+

sky_test_teacher_edit:
    path: /{id}/edit
    defaults: { _controller: SkyTestBundle:Teacher:edit }
    requirements:
        id:  \d+

sky_test_teacher_unlink:
    path: /{id}/unlink/{studentId}
    defaults: { _controller: SkyTestBundle:Teacher:unlink }
    requirements:
        id:  \d+
        studentId: \d+

sky_test_teacher_link_create:
    path: /{id}/link/{page}/{search}/{studentId}
    defaults: { _controller: SkyTestBundle:Teacher:linkCreate, page: 1, search: '' }
    requirements:
        id:  \d+
        page: \d+
        student: \d+

sky_test_teacher_link:
    path: /{id}/link/{page}/{search}
    defaults: { _controller: SkyTestBundle:Teacher:link, page: 1, search: '' }
    requirements:
        id:  \d+
        page: \d+

sky_test_teacher_index:
    path: /{id}
    defaults: { _controller: SkyTestBundle:Teacher:index  }
    requirements:
        id:  \d+