sky_test_teacher_new:
    path: /new
    defaults: { _controller: SkyTestBundle:Teacher:new  }

sky_test_teacher_index:
    path: /{id}
    defaults: { _controller: SkyTestBundle:Teacher:index  }
    requirements:
        id:  \d+