services:
    sky_test.pager:
        class: Sky\TestBundle\Pager\Pager
        arguments: [ @doctrine.orm.entity_manager ]
#    sky_test.example:
#        class: Sky\TestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
